#!/usr/bin/env node

var cli = require('../');

/**
 * Bare CLI Example
 * 
 * This example is a bare implementation of `clii`.
 * 
 */

cli('bare bones cli')
  .run( function(){
    console.log( this.name() );
  })