#!/usr/bin/env node

var cli = require('../');

cli()
  .name('basic-chain')
  .version('0.0.1')
  .option('-a, --one <string> [path]  the first option',
    function(args){ 
      console.log('one args:', JSON.stringify(args));
    })
  .option('-b, --two [number]  the second option',
    function(args){ 
      console.log('two args:', JSON.stringify(args));
    })
  .option('-c, --three [arg1|arg2|arg3]  the third option',
    function(args){ 
      console.log('three args:', JSON.stringify(args));
    })
  .option('--four  the fourth option')
  .option('--five')
  .run( function (opts, args) {
    console.log('  opts:', opts);
    console.log('  args:', args);
  })