#!/usr/bin/env node

var cli = require('../');

cli()
  .setup({
    name: 'basic example 1',
    version: '1.2.3'
  })
  .run(function(){
    console.log('  name:',this._name);
    console.log('  version:',this._version);
  })