#!/usr/bin/env node

var cli = require('../');

cli()
  .name('boolean example')
  .option('-a, --myopt  a boolean option')
  .run( function (args) {
    console.log(args);
    console.log('myopt = ', args.myopt);
  })
