#!/usr/bin/env node

var cli = require('../');

cli('my-cli v0.0.1')
  .option('-a, --my-option  this is my option')
  .run( function (args, params){
    
    // when true
    if ( args.myOption === true ) {
      console.log('has option!');
    
    // when false
    } else if ( args.myOption === false ) {
      console.log('no option.');
    
    // when everthing else, like undefined
    } else {
      console.log('option is', args.myOption);
    }
    
  })